# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  metas:
    title:        Gerkud - Gertakarien Kudeaketa

  stylesheets:    [main.css]

  javascripts: [jquery-latest.js, jquery.tablesorter.js, gerkud.js]

  has_layout:     true
  layout:         layout
